### ISSUE TITLE
Initial documentation

### ISSUE THREAD

**Issue by RyanSchuster** [RyanSchuster/vos64#3]
All items from the stable setup milestone should be included both on the wiki and in the html document versioned in the repo.
- [x] Skeleton wiki page for docs
- [x] Folder/file structure #4 
- [x] Build process and toolchain minutiae #5 
- [x] Boot process and memory layout #7 
- [x] Use of source scanners #8 
- [x] Code standards #6
